[package]
name = "proxy"
version.workspace = true
edition.workspace = true

[dependencies]
cluster = { workspace = true }
outbound = { workspace = true }
inbound = { workspace = true }
hyper = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
hyper-util = { workspace = true }
